import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Stack from '@mui/material/Stack';
import OurService from "../components/OurService";
import Section1 from "../components/Section1";
import Section2 from "../components/Section2";
import Section3 from "../components/Section3";
import OurClients from "../components/OurClients";
import ConnectForm from "../components/Connect";
import { ThemeProvider } from '@mui/material/styles';
import NavigationBar from '../components/NavigationBar';
import Footer from '../components/Footer'
import Theme from '../Theme'
// import Divider from '@mui/materi/al/Divider/Divider';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={Theme}>
        <div className="App">
          <NavigationBar />
          <Stack>
            <Section1 />
            <Section2 />
            <Section3 />
            <OurService />
            <OurClients />
            <ConnectForm />
          </Stack>
          <Footer />
        </div>
      </ThemeProvider>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
